# Вимикаємо перевірку довжини рядка (найбільш набридлива помилка)
MD013: false

# Дозволяємо кілька заголовків H1 в одному документі
MD025: false

# Дозволяємо розділові знаки в заголовках (наприклад, знаки питання)
MD026: false

# Дозволяємо HTML теги (іноді треба для картинок)
MD033: false
